---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: ping them
    ping:
  - name: Download MooseFS source code
    get_url: url=http://ppa.moosefs.com/src/moosefs-2.0.60-1.tar.gz dest=/root/moosefs.tar.gz mode=0644
  - name: Untar MooseFS source code
    unarchive: src=/root/moosefs.tar.gz dest=/root/
  - name: Configure MooseFS
    command: chdir=/root/moosefs-2.0.60 "./configure" creates=config.h
  - name: Make MooseFS
    command: chdir=/root/moosefs-2.0.60 "./make" creates=mfsnetdump/mfsnetdump
    
    
