---
- hosts: mfs-master
  connection: local
  vars:
    moosefs_dir: '/root/moosefs-2.0.60'
  tasks:
  - include: mfs-build.yml
  - name: mv configuration file mfsmaster.cfg into place
    command: mv /usr/local/etc/mfs/mfsmaster.cfg.dist /usr/local/etc/mfs/mfsmaster.cfg creates=/usr/local/etc/mfs/mfsmaster.cfg
  - name: change user to root
    lineinfile: dest=/usr/local/etc/mfs/mfsmaster.cfg insertafter=EOF line="WORKING_USER = root"
  - name: change group to wheel
    lineinfile: dest=/usr/local/etc/mfs/mfsmaster.cfg insertafter=EOF line="WORKING_GROUP = wheel"
  - name: mv configuration file mfsexports.cfg.dist into place
    command: mv /usr/local/etc/mfs/mfsexports.cfg.dist /usr/local/etc/mfs/mfsexports.cfg creates=/usr/local/etc/mfsexports.cfg
  - name: mv configuration file mfstopology.cfg.dist into place
    command: mv /usr/local/etc/mfs/mfstopology.cfg.dist /usr/local/etc/mfs/mfstopology.cfg creates=/usr/local/etc/mfstopology.cfg
  - name: start mfsmaster
    command: /usr/local/sbin/mfsmaster -a
  - name: start cgi interface
    command: /usr/local/sbin/mfscgiserv
